spring:
  application:
    name=AI
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1
  main:
    allow-bean-definition-overriding : true

  datasource:
    url: jdbc:postgresql://pgm-bp11r1xvzuv4mg41yo.rwlb.rds.aliyuncs.com:5432/springai
    username: Rigel
    password: ACE-+abc1

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.ai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

looging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor:
                SimpleLoggerAdvisor: DEBUG
